/**
 * The Comparison Section's wire shape (CLAUDE.md §13/§14, rule 14 §2) — computed by
 * `@earlysteps/comparison-engine` AFTER Assessment A and Assessment B have each
 * independently produced their own output. This is a THIRD computation, not part of either
 * engine: it never feeds back into Assessment A or Assessment B (rule 7), and its `narrative`
 * is always built from versioned content, never generated by an LLM.
 *
 * Never merge, average, or reconcile the two assessments into one number or label — this
 * type only ever states agreement / partial agreement / disagreement, with reasons.
 */
import type { ComparisonReason, ComparisonStatus, RiskBand } from './vocabulary.js';

export interface ComparisonResult {
  status: ComparisonStatus;
  /** [] iff status === 'agreement' (agreement-suppression rule — see compareAssessments). */
  reasons: ComparisonReason[];
  /** Null only when Assessment A is gated (no recommendation tier yet). */
  assessmentABand: RiskBand | null;
  assessmentBBand: RiskBand;
  /** Null iff assessmentABand is null. */
  bandDistance: 0 | 1 | 2 | null;
  /** Deterministic, templated from versioned content — NEVER LLM-generated. */
  narrative: string;
  computedAt: string;
}
